suggest blades
Cray-HPE/cani pull request #105
Opened 2023-08-01 11:23 UTC by jacobsalmela

# Summary and Scope

- add `--auto` and `--accept` flags to `add blade`
- adds ordinal field to hardwaretypes library
- adds required networks to no hardware fixture

# Risks and Mitigations

2023-08-04 19:29 UTC, shunr-hpe commented on internal/provider/csm/recommend.go
> +			if metadata.Cabinet.HMNVlan != nil {
metadata.Cabinet == nil can probably never happen since cabinets are always created with a vlan.
however if metadata is nil, would we still want to count the LocationOrdinal?

If so maybe collapse to
if metadata.Cabinet != nil && metadata.Cabinet.HMNVlan != nil {
...

2023-08-04 19:46 UTC, rsjostrand-hpe commented on testdata/fixtures/sls/no_hardware.json
>      "Networks": {}
Your PR description says you added required networks to this file, but I don't see any?

2023-08-04 19:46 UTC, jacobsalmela commented on internal/provider/csm/recommend.go
> +			if metadata.Cabinet.HMNVlan != nil {
This was existing from before (just moved to this new file), but fixed!

2023-08-04 19:47 UTC, jacobsalmela commented on testdata/fixtures/sls/no_hardware.json
>      "Networks": {}
I left it off instead since it didn't really apply to this PR.  I was using it for testing at one point.  I'll make a follow up PR for it

2023-08-04 19:47 UTC, jacobsalmela commented on testdata/fixtures/sls/no_hardware.json
>      "Networks": {}
Guess  my line endings ended up here in any case

2023-08-04 19:57 UTC, jacobsalmela commented on testdata/fixtures/sls/no_hardware.json
>      "Networks": {}
https://github.com/Cray-HPE/cani/pull/114

2023-08-04 20:05 UTC, rsjostrand-hpe approved these changes

2023-08-22 14:43 UTC, shunr-hpe approved these changes

2023-08-22 14:45 UTC, rsjostrand-hpe requested changes

2023-08-22 15:08 UTC, jacobsalmela commented on testdata/fixtures/sls/no_hardware.json
>      "Networks": {}
fixed

2023-08-22 15:08 UTC, jacobsalmela commented on pkg/hardwaretypes/library.go
> +type HardwareBuildOut struct {
I knew that, too.  Fixed

2023-08-22 15:20 UTC, rsjostrand-hpe commented on pkg/hardwaretypes/library.go
> +type HardwareBuildOut struct {
Looks like the regex is still present in the other code: https://github.com/Cray-HPE/cani/blob/careful-whirlwind/internal/inventory/buildout.go#L135-L142

Did all of your ordinal stuff make it over to the new spot?

2023-08-22 15:35 UTC, shunr-hpe approved these changes

2023-08-22 16:41 UTC, jacobsalmela commented on pkg/hardwaretypes/library.go
> +type HardwareBuildOut struct {
Now it is there.

2023-08-22 16:42 UTC, rsjostrand-hpe approved these changes

2023-08-22 16:45 UTC, merged