Reconcile and import improvements
Cray-HPE/cani pull request #79
Opened 2023-06-26 18:04 UTC by rsjostrand-hpe

# Summary and Scope

Reconcile Improvements:
* Added provider defaults to hardware type library. This provides a place to specify the expected CSM hardware class for a piece of hardware, instead of hardcoding it. Right now only Cabinets need it.
* Properly generate cabinet network metadata for SLS hardware objects.
* Properly determine hardware class for SLS hardware objects Mountain/Hill/River. Instead of having an hardcode of mountain. 

Import improvements
* Added model information for other supported blade types to the hardware type library.

## Testing
Started the HSM Simulation environment with no hardware and loaded SLS with sls_input_file.json describing a system with a Hill cabinet.

Start session.
```
(venv) [~/Documents/Github/cani]$ go run . alpha session start csm -S -k                                                                                 *[import-improvements]
11:38AM WRN Using simulation mode
11:38AM INF /Users/ryansjostrand/.cani/canidb.json does not exist, creating default datastore
11:38AM INF Validated CANI inventory
2023/06/27 11:38:13 [DEBUG] GET https://localhost:8443/apis/sls/v1/dumpstate
11:38AM INF Validated external inventory provider
11:38AM INF Session is now ACTIVE with provider csm and datastore /Users/ryansjostrand/.cani/canidb.json
```

Import. HSM had no data init, so no node hardware was pulled in.
```bash
(venv) [~/Documents/Github/cani]$ go run . alpha session import                                                                                          *[import-improvements]
11:38AM INF Session is STOPPED
11:38AM INF Committing changes to session
2023/06/27 11:38:26 [DEBUG] GET https://localhost:8443/apis/sls/v1/dumpstate
2023/06/27 11:38:26 [DEBUG] GET https://localhost:8443/apis/smd/hsm/v2/State/Components
2023/06/27 11:38:26 [DEBUG] GET https://localhost:8443/apis/smd/hsm/v2/Inventory/Hardware
11:38AM INF Cabinet x9000 does not exist in datastore at System:0->Cabinet:9000
11:38AM INF Cabinet x9000 device type slug is hpe-ex2000
11:38AM INF Hardware from cabinet x9000: a3642db0-6ebd-4038-af27-a4f07f995592
11:38AM INF Hardware from cabinet x9000: ca7353c7-90c1-47f8-ae71-8fc7b63502da
11:38AM INF Hardware from cabinet x9000: 5e4d69e8-d849-406c-abe6-791df35a7a6c
11:38AM INF Hardware from cabinet x9000: e3393d22-02ce-40d8-838a-61e9133f8f7d
11:38AM INF Hardware from cabinet x9000: cd378b63-3fb1-4602-8fac-d1dd871776ea
11:38AM INF Hardware from cabinet x9000: 5be3c9ef-50ed-4579-a9c0-9e4bc60994fd
11:38AM WRN Detected CANI hardware ID change from 714a3a48-45ee-4699-9364-da2a4538f65a to a3642db0-6ebd-4038-af27-a4f07f995592 for SLS Hardware x9000
11:38AM INF SLS extra properties changed for x9000
11:38AM WRN Detected CANI hardware ID change from 9a7d8c03-e2cc-4d19-bee5-fde307699d61 to e3393d22-02ce-40d8-838a-61e9133f8f7d for SLS Hardware x9000c3
11:38AM INF SLS extra properties changed for x9000c3
11:38AM WRN Detected CANI hardware ID change from e2a2d985-59f0-469d-ac3a-f30bdc44ea24 to 5e4d69e8-d849-406c-abe6-791df35a7a6c for SLS Hardware x9000c1
11:38AM INF SLS extra properties changed for x9000c1
11:38AM WRN Detected CANI hardware ID change from 2d454b45-5c8e-40b6-9fb2-275edeb0d973 to cd378b63-3fb1-4602-8fac-d1dd871776ea for SLS Hardware x9000c1b0
11:38AM INF SLS extra properties changed for x9000c1b0
11:38AM WRN Detected CANI hardware ID change from 85f1c18b-8d69-41ab-bc67-1f9445db3123 to 5be3c9ef-50ed-4579-a9c0-9e4bc60994fd for SLS Hardware x9000c3b0
11:38AM INF SLS extra properties changed for x9000c3b0
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:3->NodeBlade:7->NodeCard:1->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:2->NodeCard:1->Node:0
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:6->NodeCard:1->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:3->NodeBlade:5->NodeCard:1->Node:0
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:3->NodeBlade:2->NodeCard:1->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:4->NodeCard:1->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:3->NodeBlade:0->NodeCard:0->Node:0
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:1->NodeCard:1->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:3->NodeBlade:7->NodeCard:0->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:3->NodeBlade:4->NodeCard:1->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:3->NodeBlade:1->NodeCard:0->Node:0
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:2->NodeCard:0->Node:0
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:4->NodeCard:0->Node:0
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:5->NodeCard:0->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:3->NodeBlade:7->NodeCard:0->Node:0
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:3->NodeBlade:0->NodeCard:1->Node:0
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:2->NodeCard:0->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:0->NodeCard:0->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:3->NodeBlade:2->NodeCard:0->Node:0
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:3->NodeBlade:4->NodeCard:0->Node:0
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:5->NodeCard:0->Node:0
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:0->NodeCard:0->Node:0
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:3->NodeBlade:0->NodeCard:1->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:7->NodeCard:0->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:4->NodeCard:1->Node:0
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:3->NodeCard:0->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:7->NodeCard:1->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:4->NodeCard:0->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:6->NodeCard:0->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:3->NodeBlade:3->NodeCard:0->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:1->NodeCard:0->Node:1
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:6->NodeCard:0->Node:0
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:3->NodeBlade:7->NodeCard:1->Node:0
11:38AM WRN Hardware does not exist (possible phantom hardware): System:0->Cabinet:9000->Chassis:1->NodeBlade:5->NodeCard:1->Node:0
11 [...]

2023-06-26 21:27 UTC, jacobsalmela requested changes

2023-06-26 21:27 UTC, jacobsalmela commented on Makefile
> +	docker run -it --rm -v $$(pwd):/github/workspace artifactory.algol60.net/csm-docker/stable/license-checker .github/workflows/ cmd/ internal pkg/hardwaretypes pkg/xname --fix
Why the double `$$`?  Maybe this should just be the env var instead `$PWD`

2023-06-27 16:34 UTC, rsjostrand-hpe commented on Makefile
> +	docker run -it --rm -v $$(pwd):/github/workspace artifactory.algol60.net/csm-docker/stable/license-checker .github/workflows/ cmd/ internal pkg/hardwaretypes pkg/xname --fix
`make license` doesn't work without it. `$(pwd)` evaluated to an empty string. I added the second `$` so make would run `$(pwd)` with bash/shell assuming I read the stuff I found online right.   
```bash
docker run -it --rm -v :/github/workspace artifactory.algol60.net/csm-docker/stable/license-checker .github/workflows/ cmd/ internal pkg/hardwaretypes pkg/xname --fix
```

`$PWD` does not work:
```bash
docker run -it --rm -v WD:/github/workspace artifactory.algol60.net/csm-docker/stable/license-checker .github/workflows/ cmd/ internal pkg/hardwaretypes pkg/xname --fix
```

`${PWD}` works. I'll go with this one.
```bash
docker run -it --rm -v /Users/ryansjostrand/Documents/Github/cani:/github/workspace artifactory.algol60.net/csm-docker/stable/license-checker .github/workflows/ cmd/ internal pkg/hardwaretypes pkg/xname --fix
```

2023-06-27 17:47 UTC, jacobsalmela commented on Makefile
> +	docker run -it --rm -v $$(pwd):/github/workspace artifactory.algol60.net/csm-docker/stable/license-checker .github/workflows/ cmd/ internal pkg/hardwaretypes pkg/xname --fix
I suppose it is on me for not testing the actual `make` command; I just pasted in the working one from the terminal.

What you did works.  Usually, this works, too to call out to other commands: `$(shell pwd)`

2023-06-27 18:17 UTC, jacobsalmela approved these changes

2023-06-27 18:17 UTC, merged