show procedure to fix missing HMN_MTN and NMN_MTN networks for csm pr…
Cray-HPE/cani pull request #89
Opened 2023-07-10 19:51 UTC by jacobsalmela

…ovider

# Summary and Scope

# Risks and Mitigations

2023-07-11 15:04 UTC, rsjostrand-hpe requested changes

2023-07-11 15:04 UTC, rsjostrand-hpe commented on docs/troubleshooting/known_errors.md
> +> Note: update the site-specific information as needed (IP, MTU, VLANs, etc.)
The MTU value shouldn't be changed.

2023-07-11 15:04 UTC, rsjostrand-hpe commented on docs/troubleshooting/known_errors.md
> +> Note: update the site-specific information as needed (IP, MTU, VLANs, etc.)
The MTU value shouldn't be changed.

2023-07-11 15:04 UTC, rsjostrand-hpe commented on docs/troubleshooting/known_errors.md
> +```shell
Let's consider just specify the CrayCLI commands.

If we keep the curl commands they are missing the authentication token.

I wonder if we need to cover the following scenarios, and split the commands for each scenario into a subsection and follow the one the applies.
* Cray CLI (the steps would be the same on and off the cluster)
* Curl when on a `ncn-*` node, targeting the normal/NMN API gateway
* Curl when on a remote system targeting the CMN API Gateway.

2023-07-11 15:51 UTC, jacobsalmela commented on docs/troubleshooting/known_errors.md
> +> Note: update the site-specific information as needed (IP, MTU, VLANs, etc.)
Fixed

2023-07-11 15:51 UTC, jacobsalmela commented on docs/troubleshooting/known_errors.md
> +Here is an example HMN_MTN JSON file that creates the network when patched into SLS.
Fixed

2023-07-11 15:58 UTC, rsjostrand-hpe commented on docs/troubleshooting/known_errors.md
> +  ]
```
  "VlanRange": [
    2000,
    2999
  ]
```

2023-07-11 16:01 UTC, jacobsalmela commented on docs/troubleshooting/known_errors.md
> +    ]
Fixed

2023-07-11 16:01 UTC, jacobsalmela commented on docs/troubleshooting/known_errors.md
> +  ]
Fixed

2023-07-12 18:03 UTC, rsjostrand-hpe approved these changes

2023-07-12 18:03 UTC, merged